2019-07-27 00:00:00,601	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:00] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:16,011	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:16] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:18,367	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:18] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:31,379	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:31] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:31,831	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:31] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:37,415	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:37] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:41,269	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:41] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:44,851	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:44] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:48,022	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:48] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:00:50,629	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:00:50] "GET /course/details/ HTTP/1.1" 200 -
2019-07-27 00:01:09,798	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:01:09] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:01:29,097	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:01:29] "OPTIONS /course/ HTTP/1.1" 200 -
2019-07-27 00:01:29,101	ERROR	app	log_exception	Line:1761	Exception on /course/ [POST]
Traceback (most recent call last):
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/bin/anaconda3/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/long/development/classarrangement/services/apis/courseAPI.py", line 22, in post
    return CourseDAO.addcourse(api.payload)
  File "/home/long/development/classarrangement/services/daos/courseDAO.py", line 94, in addcourse
    course_isgroup = cou["course_isgroup"]
KeyError: 'course_isgroup'
2019-07-27 00:01:29,102	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:01:29] "POST /course/ HTTP/1.1" 500 -
2019-07-27 00:03:14,877	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:03:14] "GET /class/ HTTP/1.1" 200 -
2019-07-27 00:03:28,224	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:03:28] "OPTIONS /course/ HTTP/1.1" 200 -
2019-07-27 00:03:28,229	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:03:28] "POST /course/ HTTP/1.1" 200 -
2019-07-27 00:03:28,239	INFO	_internal	_log	Line:88	127.0.0.1 - - [27/Jul/2019 00:03:28] "GET /course/details/ HTTP/1.1" 200 -
2019-07-27 00:03:40,147	INFO	_internal	_log	Line:88	 * Detected change in '/home/long/development/classarrangement/services/daos/courseDAO.py', reloading
